# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
host:             localhost
port:             9001
baseurl:          ""
url:              https://georgetown-university.github.io/bootstrap-documentation
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  4.0.0-alpha.2
repo:             https://github.com/twbs/bootstrap
slack:            https://bootstrap-slack.herokuapp.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  css_hash:       "sha384-XXXXXXXX"
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  js_hash:        "sha384-XXXXXXXX"
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
